### ISSUE TITLE
i try install to Laravel 9.27.0

### ISSUE THREAD

**Issue by halowahyudi** [laravel-ready/license-server#2]
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Root composer.json requires laravel-ready/license-server ^1.2 -> satisfiable by laravel-ready/license-server[1.2.4].
    - laravel-ready/license-server 1.2.4 requires laravel/sanctum ^2.15 -> found laravel/sanctum[v2.15.0, v2.15.1, 2.x-dev] but it conflicts with your root 
composer.json require (^3.0).

Use the option --with-all-dependencies (-W) to allow upgrades, downgrades and removals for packages currently locked to specific versions.

Installation failed, reverting ./composer.json and ./composer.lock to their original content.

**Comment by relliv** [comment]
Ok, laravel 9 is supporting now. You can try to install it again. Also, you need to check these [requirement](https://github.com/laravel-ready/license-server#-requirements) notes.
