### ISSUE TITLE
Support for transferable license

### ISSUE THREAD

**Issue by rjjrbatarao** [laravel-ready/license-server#3]
Is there a way to transfer license to another user? Im looking for a way to do this, thank you

**Comment by relliv** [comment]
Hi, this package currently provides limited features and no license transfer feature. You can do it manually, using [License](https://github.com/laravel-ready/license-server/blob/main/src/Models/License.php) model and updating `use_id`.

> note: I will publish v2.0 in a few days (and comes with API breaking changes). Maybe I can add it.
