### ISSUE TITLE
Laravel 10

### ISSUE THREAD

**Issue by ppalashturov** [laravel-ready/license-server#6]
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - laravel-ready/license-server[1.0.1, ..., 1.2.7] require illuminate/support ^9.0 -> found illuminate/support[v9.0.0, ..., v9.52.6] but these were not loaded, likely because it conflicts with another require.
    - Root composer.json requires laravel-ready/license-server * -> satisfiable by laravel-ready/license-server[1.0.1, ..., 1.2.7].

You can also try re-running composer require with an explicit version constraint, e.g. "composer require laravel-ready/license-server:*" to figure out if any version is installable, or "composer require laravel-ready/license-server:^2.1" if you know which you need.

**Comment by relliv** [comment]
@ppalashturov Laravel 10 supporting now, can you try again?

**Comment by ppalashturov** [comment]
Thanks!
